GET http://localhost:8000/products/ HTTP/1.1

###

GET http://localhost:8000/products/2/ HTTP/1.1

###

DELETE http://localhost:8000/products/2/ HTTP/1.1

###

PUT http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NzcyOTc4LCJpYXQiOjE3MzY3NzI2NzgsImp0aSI6IjQzYmZhMWVmZDVkNTQ5M2ZiN2MxYTJiMDJiMTg4ZDIwIiwidXNlcl9pZCI6MX0.5M08j6EIq0KrAoUoHDLmjZp_oA2r3ENb0z_1ShoFnxw


{
  "name": "Television",
  "price": 300.00,
  "stock": 14,
  "description": "An amazing new TV"
}

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NjkyNzg3LCJpYXQiOjE3MzY2OTI0ODcsImp0aSI6IjNlZDk2NmVmNTYzMDQyYWRhYWUxMjc0ZDBjMDQ5ZmMzIiwidXNlcl9pZCI6MX0.bLbQBoMvT22Dh3cYBvBugqFl_RHjvgqtedwwCCGMzoU

{
  "name": "Television",
  "price": 300.00,
  "stock": 14,
  "description": "An amazing new TV"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
  "username": "onion",
  "password": "onion2132?"
}

###

GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NjkyNzg3LCJpYXQiOjE3MzY2OTI0ODcsImp0aSI6IjNlZDk2NmVmNTYzMDQyYWRhYWUxMjc0ZDBjMDQ5ZmMzIiwidXNlcl9pZCI6MX0.bLbQBoMvT22Dh3cYBvBugqFl_RHjvgqtedwwCCGMzoU

###

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNjc3OTMwMCwiaWF0IjoxNzM2NjkyOTAwLCJqdGkiOiIwNTE1NzdkM2IwZDA0NzA4OWI3YjUzZGI3ZGE2OTgwNiIsInVzZXJfaWQiOjF9.hfmKDiX6f-P0u0AIttrYyKaz4QX4I7lPYB6vxROkfXk"
}

###

GET http://localhost:8000/orders/31352a6b-46a7-4b85-a543-03ed7afb2421 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4NDA4MjI0LCJpYXQiOjE3Mzg0MDc5MjQsImp0aSI6IjU5NGNjYTQ0MDlmODQzYzY4NjkyMzFhZGFjMTYxOTBkIiwidXNlcl9pZCI6Mn0._lSSi3whzcP9bc7eLiOAGeEWu9xNfxq_Q8l2Z1a8IlQ