GET http://localhost:8000/products/ HTTP/1.1

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NjkyNzg3LCJpYXQiOjE3MzY2OTI0ODcsImp0aSI6IjNlZDk2NmVmNTYzMDQyYWRhYWUxMjc0ZDBjMDQ5ZmMzIiwidXNlcl9pZCI6MX0.bLbQBoMvT22Dh3cYBvBugqFl_RHjvgqtedwwCCGMzoU

{
  "name": "Television",
  "price": 300.00,
  "stock": 14,
  "description": "An amazing new TV"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "midknight1!"
}

###

GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NjkyNzg3LCJpYXQiOjE3MzY2OTI0ODcsImp0aSI6IjNlZDk2NmVmNTYzMDQyYWRhYWUxMjc0ZDBjMDQ5ZmMzIiwidXNlcl9pZCI6MX0.bLbQBoMvT22Dh3cYBvBugqFl_RHjvgqtedwwCCGMzoU

###

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNjc3OTMwMCwiaWF0IjoxNzM2NjkyOTAwLCJqdGkiOiIwNTE1NzdkM2IwZDA0NzA4OWI3YjUzZGI3ZGE2OTgwNiIsInVzZXJfaWQiOjF9.hfmKDiX6f-P0u0AIttrYyKaz4QX4I7lPYB6vxROkfXk"
}