### 제품 목록
GET http://localhost:8000/products/ HTTP/1.1

### 제품 상세
GET http://localhost:8000/products/2/ HTTP/1.1

### 제품 삭제
DELETE http://localhost:8000/products/2/ HTTP/1.1

### 제품 수정
PUT http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NzcyOTc4LCJpYXQiOjE3MzY3NzI2NzgsImp0aSI6IjQzYmZhMWVmZDVkNTQ5M2ZiN2MxYTJiMDJiMTg4ZDIwIiwidXNlcl9pZCI6MX0.5M08j6EIq0KrAoUoHDLmjZp_oA2r3ENb0z_1ShoFnxw


{
  "name": "Television",
  "price": 300.00,
  "stock": 14,
  "description": "An amazing new TV"
}

### 제품 등록
POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NjkyNzg3LCJpYXQiOjE3MzY2OTI0ODcsImp0aSI6IjNlZDk2NmVmNTYzMDQyYWRhYWUxMjc0ZDBjMDQ5ZmMzIiwidXNlcl9pZCI6MX0.bLbQBoMvT22Dh3cYBvBugqFl_RHjvgqtedwwCCGMzoU

{
  "name": "Television",
  "price": 300.00,
  "stock": 14,
  "description": "An amazing new TV"
}

### 사용자 인증 토큰
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "midknight1!"
}

### 사용자 주문 목록
GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4NDEzNjUzLCJpYXQiOjE3Mzg0MTMzNTMsImp0aSI6IjQ2ZDIwNDgwOWU0YTQxMzBhNGFjOTNjOWFhNTdjYzRjIiwidXNlcl9pZCI6MX0.O8XouALifZdH1H4VrObJt_rHYYQJQDqga8JRuVyLQLM

### 사용자 인증 토큰 재생성
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNjc3OTMwMCwiaWF0IjoxNzM2NjkyOTAwLCJqdGkiOiIwNTE1NzdkM2IwZDA0NzA4OWI3YjUzZGI3ZGE2OTgwNiIsInVzZXJfaWQiOjF9.hfmKDiX6f-P0u0AIttrYyKaz4QX4I7lPYB6vxROkfXk"
}

### 주문 상세
GET http://localhost:8000/orders/19fe8e1c-12b3-4ea5-9400-0b1211f800bb/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4NDE1MjYzLCJpYXQiOjE3Mzg0MTQ5NjMsImp0aSI6IjJhMjM1YTMyYmI0MjQ2YWZiNDI2NzM3MjhiMTc0ZDI4IiwidXNlcl9pZCI6MX0.OaautqazrRHTWRGO7twJrHMCcmW29ozy7VTUoflVuDI

### 주문 등록
POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4NDEyNTU3LCJpYXQiOjE3Mzg0MTIyNTcsImp0aSI6IjhhZWIzYTgxMmY1ZjRiNjhiNWMyY2NlZTMwM2FhMDBkIiwidXNlcl9pZCI6MX0.iyWffkoxcxLclbLPNgx0PpgZkw6QqJtAzEORPT3XuTw

{
  "status": "Pending",
  "items": [
    {
      "product": 2,
      "quantity": 2
    },
    {
      "product": 3,
      "quantity": 1
    }
  ]
}

### 주문 수정
PUT http://localhost:8000/orders/19fe8e1c-12b3-4ea5-9400-0b1211f800bb/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4NDE0OTQ2LCJpYXQiOjE3Mzg0MTQ2NDYsImp0aSI6ImQwMTdjNjA2Yjg5MzQ5ZjU5NWY3ODAyNDAxYmYzYzkxIiwidXNlcl9pZCI6MX0.P9h2YRVn2ScRHVf3T7ZkSfqxm-frZ2sW4JBBU4bdAtY

{
  "status": "Confirmed"
}

### 주문 삭제
DELETE http://localhost:8000/orders/19fe8e1c-12b3-4ea5-9400-0b1211f800bb/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4NDE1MjYzLCJpYXQiOjE3Mzg0MTQ5NjMsImp0aSI6IjJhMjM1YTMyYmI0MjQ2YWZiNDI2NzM3MjhiMTc0ZDI4IiwidXNlcl9pZCI6MX0.OaautqazrRHTWRGO7twJrHMCcmW29ozy7VTUoflVuDI
